// Copyright 2026 Niuarque B. Rosa and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"olx-pp-cli/internal/cliutil"
)

func newCrawlBuscarAnunciosCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagCategoria string
	var flagPagina int
	var flagSort string
	var flagMinPreco float64
	var flagMaxPreco float64
	var flagLocalizacao string
	var bodyPriority int
	var bodyUrls string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "buscar-anuncios",
		Aliases:     []string{"create"},
		Short:       "Busca anúncios na OLX com filtros. Constrói a URL da OLX a partir dos parâmetros: - Com categoria: /<categoria-path>?",
		Example:     "  olx-pp-cli crawl buscar-anuncios",
		Annotations: map[string]string{"pp:endpoint": "crawl.buscar-anuncios", "pp:method": "POST", "pp:path": "/crawl"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{"", "date", "price_asc", "price_desc"}
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagSort, "sort", allowedSort)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/crawl"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyPriority != 0 {
					body["priority"] = bodyPriority
				}

				// Construir URL da OLX a partir dos parâmetros
				olxURL := buildOlxURL(flagQ, flagCategoria, flagPagina, flagSort, flagMinPreco, flagMaxPreco, flagLocalizacao)
				if bodyUrls != "" {
					// Se --urls foi passado explicitamente, usar ele
					body["urls"] = cliutil.SplitCSV(bodyUrls)
				} else {
					body["urls"] = []string{olxURL}
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "crawl", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "crawl", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "crawl", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "crawl", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "crawl", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "crawl",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "crawl", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "crawl", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagQ, "q", "", "Termo de busca")
	cmd.Flags().StringVar(&flagCategoria, "categoria", "", "Caminho amigável da categoria (ex: informatica/notebooks, celulares, imoveis/venda")
	cmd.Flags().IntVar(&flagPagina, "pagina", 1, "Número da página")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Ordenação: (vazio)=relevância, date=mais recentes, price_asc=menor preço, price_desc=maior preço (one of: , date, price_asc, price_desc)")
	cmd.Flags().Float64Var(&flagMinPreco, "min-preco", 0.0, "Preço mínimo")
	cmd.Flags().Float64Var(&flagMaxPreco, "max-preco", 0.0, "Preço máximo")
	cmd.Flags().StringVar(&flagLocalizacao, "localizacao", "", "Slug da localização. Ex: estado-sp, rio-de-janeiro-e-regiao, distrito-federal, grande-goiania-e-anapolis, minas-gerais")
	cmd.Flags().IntVar(&bodyPriority, "priority", 10, "Priority")
	cmd.Flags().StringVar(&bodyUrls, "urls", "", "URL da OLX para buscar (construída pelo CLI a partir dos parâmetros)")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}

// buildOlxURL constrói a URL da OLX a partir dos parâmetros de busca.
func buildOlxURL(q, categoria string, pagina int, sort string, minPreco, maxPreco float64, localizacao string) string {
	baseURL := "https://www.olx.com.br"

	// Montar path: /categoria/localizacao
	// A OLX usa a ordem: /<categoria>/<estado>/<regiao>/<cidade>
	var pathParts []string
	if categoria != "" {
		pathParts = append(pathParts, categoria)
	}
	if localizacao != "" {
		pathParts = append(pathParts, localizacao)
	}

	var path string
	if len(pathParts) > 0 {
		path = baseURL + "/" + strings.Join(pathParts, "/")
	} else {
		path = baseURL + "/brasil"
	}

	// Montar query string
	query := url.Values{}
	if q != "" {
		query.Set("q", q)
	}
	if pagina > 1 {
		query.Set("o", fmt.Sprintf("%d", pagina))
	}
	if sort != "" {
		query.Set("ps", sort)
	}
	if minPreco > 0 {
		query.Set("minPrice", fmt.Sprintf("%.0f", minPreco))
	}
	if maxPreco > 0 {
		query.Set("maxPrice", fmt.Sprintf("%.0f", maxPreco))
	}

	if len(query) > 0 {
		return path + "?" + query.Encode()
	}
	return path
}
