// Copyright 2026 Niuarque B. Rosa and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCrawlCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "crawl",
		Short:       "CLI para buscar e consultar anúncios da OLX Brasil.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCrawlBuscarAnunciosCmd(flags))
	cmd.AddCommand(newCrawlDetalhesAnuncioCmd(flags))
	cmd.AddCommand(newCrawlListarCategoriasCmd(flags))
	return cmd
}
